#!/bin/bash

if [ -e "Makefile" ]; then
	echo "Running make clean..."
  make clean 2>&1 >/dev/null
fi

echo -ne "Removing binary directories: "
BIN_DIRS=( "bin" "src/bin" )
for BIN_DIR in "${BIN_DIRS[@]}"; do
	if [ -d "${BIN_DIR}" ]; then
		echo -ne "${BIN_DIR} "
		rm -r "${BIN_DIR}"
	fi
done
echo -ne "\n"

echo -ne "Removing make files: "
MAKE_FILES=( "CMakeCache.txt" "Makefile"  "CMakeFiles" "cmake_install.cmake" )
for MAKE_FILE in "${MAKE_FILES[@]}"; do
	echo -ne "${MAKE_FILE} "
	find . -name "${MAKE_FILE}" -print0 | xargs -0 /bin/rm -rf
done
echo -ne "\n"

echo -ne "Removing files with extension: "
EXTENSIONS=( ".a" ".pyc" )
for EXTENSION in "${EXTENSIONS[@]}"; do
	echo -ne "${EXTENSION} "
	find . -name "*${EXTENSION}" -delete
done
echo -ne "\n"

echo "Done."
